### ISSUE TITLE
Algorithm strength?

### ISSUE THREAD

**Issue by sergeevabc** [jcoglan/vault#26]
Dear James,
I'm looking for the most reasonable implementation of online password hasher for the years ahead. Have found none so far, yet tried every related extension from Chrome Webstore along with Github projects.

For example, Saltthepass.com produces `x = Trim(Base64(SHA3(Master Password + Domain Name + Domain Phrase)))`, which means the developer oversimplifies proper theory behind hashing: “[Password Hashing Competition][4]”, “[Storing passwords securely][5]”, “[Salted Password Hashing - Doing it Right][3]”.

Let's examine your solution. Questions and doubts arise as I see that PBKDF2 seems to be used without HMAC-SHA256 at least, number of rounds/iterations is neither clearly stated nor changeable, some UUID is hard-coded, relatively outdated CryptoJS is used instead of modern [SLSJ][1], [ASMCrypto][7] or [FastJS][2], and “max repetition” parameter is neither documented nor self-explanatory. (For example, Oneshallpass.com, which uses PBKDF2-HMAC-SHA512, is [well-documented][6], but its front-end is cumbersome, alas.)

In the end, James, could you tell if Vault is going to be tighten up and how?

[1]: https://github.com/bitwiseshiftleft/sjcl
[2]: https://github.com/dchest/fast-sha256-js
[3]: https://crackstation.net/hashing-security.htm
[4]: https://password-hashing.net/faq.html
[5]: http://throwingfire.com/storing-passwords-securely/
[6]: https://github.com/maxtaco/oneshallpass/blob/master/README.md
[7]: https://github.com/vibornoff/asmcrypto.js/

**Comment by jcoglan** [comment]
@sergeevabc Did my last comment answer your question, and if so can I close this issue?
