### ISSUE TITLE
"Your .vault file is unreadable"

### ISSUE THREAD

**Issue by co-dan** [jcoglan/vault#33]
Recently I started having the following problem when running vault:

> (node:68295) DeprecationWarning: crypto.pbkdf2 without specifying a digest is deprecated. Please specify a digest
> Your .vault file is unreadable; check your VAULT_KEY and VAULT_PATH settings

This is the result of any command. I guess something happened with my .vault file or some other settings. I don't think I ever set VAULT_KEY or VAULT_PATH variables.

Unfortunately, I am not sure how to debug this issue. Any help would be appreciated.

PS thanks for your app

**Comment by jcoglan** [comment]
I assume from the deprecation warning you're running Node 6. Is that correct? Are you able to use Vault with a different Node version?

Which versions of `vault` and `vault-cipher` do you have installed?

**Comment by co-dan** [comment]
Yes, I am running node v6.2.1. I have vault version 2.0 installed and as far as I know I don't have a package named vault-cipher installed. 

I think some auto-update of node triggered this whole thing. But, anyway, I nuked vault and reinstalled the latest version (which happens to be 0.3.0 in my case?), and it seems to be working with my old .vault file. Yay!

So, yeah, sorry for bothering you with this then :)
