### ISSUE TITLE
What is the correct license?

### ISSUE THREAD

**Issue by mstum** [jcoglan/vault#35]
The getvau.lt website says it's MIT on https://getvau.lt/faq.html, but the repository says GPLv3

Since there is an explicit commit to change the license to GPLv3 I assume that's the correct license, but I wanted to double check beforehand.

Thanks!

**Comment by jcoglan** [comment]
The website is still serving v0.3, which was released under the MIT license. v0.4 is not yet released but will be under GPLv3.
